name: generic_json_serializable
description: generic serialize
version: 0.0.1
homepage: https://github.com/wenjunxiao/generic_json_serializable.dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.5.0'
  path: ^1.3.2
  glob: ^1.1.0
  source_gen: ^0.9.0
  analyzer: ^0.39.3
  generic_json_annotation: ^0.0.1


dev_dependencies:
  build_runner: ^1.0.0
  source_gen_test: ^0.1.0
  test: ^1.6.0
